<?php

namespace ActiveProxy\Utils;

class Signal
{
    const SIGNAL_HEARTBEAT = 'SSHPROXY-HEARTBEAT';
    const SIGNAL_PROXY_CONNECT = 'SSHPROXY_PROXY_CONNECT';
    const SIGNAL_CONTROL_CONNECT = 'SSHPROXY_CONTROL_CONNECT';
    const SIGNAL_PROXY_READY = 'SSHPROXY_CONNECTION_READY';

    const COMMAND_SET_SSH_ADDRESS = 'SET_SSH_ADDRESS';
}